### ISSUE TITLE
Request: Astrologian

### ISSUE THREAD

**Issue by Samidaro** [MKhayle/XIVComboExpanded#176]
Can you please add a "Celestial Intersection" into "Celestial Opposition" 
Thanks

**Comment by daemitus** [comment]
Is this for a mash button? I don't get the idea behind combining a single target with an aoe.

**Comment by Samidaro** [comment]
i usually just use it every time it's available and there is damage coming, and it has a 60 sec CD, so i'd like it to be just used. Maybe it would be better on aspected helios . Not sure

**Comment by kaedys** [comment]
I'm not sure of the logic of combining it with Celestial Intersection, especially since Celestial Intersection is definitely the priority of the two (much more likely to save the target, especially a tank), _and_ has charges on it after level 88.  Aspected Helios would almost certainly be a better option, since Celestial Opposition is essentially an oGCD version of Aspected Helios (the latter being stronger after level 85, but before they they're identical in function, aside from the GCD vs oGCD).  In nearly all cases where you'd drop a GCD for Aspected Helios, if Celestial Opposition is available, you'd probably want to use it first (or, potentially, as well, if the damage is high enough, since the HoT effects stack).

**Comment by MKhayle** [comment]
Both spells have entirely different purposes and shouldn't be used as a combo, especially not now that Celestial Intersection has 2 charges.
(It's a bit late of an answer, sorry.)
