### ISSUE TITLE
Request: Have Soul Slice/Soul Scythe be a part of their respective combos

### ISSUE THREAD

**Issue by EnixLHQ** [MKhayle/XIVComboExpanded#195]
Requesting to have Soul Slice and Soul Scythe be a part of the single-target and AoE combos, respectively, whenever Soul Gauge is <50. Additionally, the Soul Slice to Soul Scythe feature could cooperate with this so that it detects which to use based on the combo string in use.

Currently, even though Soul Slice and Soul Scythe can switch between ST and AoE forms, it is an additional button that does not have an option to be bundled with the rest of the combo strings.

**Comment by kaedys** [comment]
I can see why someone would want this, but it strikes me as likely to lead to a DPS loss rather than gain.  If you hit a button that normally gives you 10 Soul Gauge and instead suddenly gain 50, even if that doesn't cap you, you were probably spamming that button again to hit the next combo attack and _now_ you may overcap.  Only way I think this'd be reasonable is if it also automates the Bloodstalk -> Gibbet/Gallows, and then we're into territory of the mod automating usage of positionals when you may not be expecting them to be used.

Actually, nevermind, looking at the code, it looks like that's already a combo option.  If we already have automation of the Bloodstalk + Gibbet/Gallows, I see very little reason that Soul Slice/Soul Scythe couldn't be integrated.  While we're at it, can also integrate Shadow of Death refreshing (obviously, that has some issue with double Enshroud windows, but if you're merging that many abilities into one key, you _probably_ shouldn't be worrying about double Enshrouds or any similar advanced optimization concept).

**Comment by MKhayle** [comment]
hello! this is dawntrail time, I am still lvl 74 as a reaper, I never took the time to understand whatever this issue was about because it used words I didn't comprehend and will probably look into it once the DT issues are done with

you can remind me by the end of july if I didn't do it

**Comment by MKhayle** [comment]
@kaedys could you give a second look at this because I'm not sure it's still relevant post-EW and I'm not familiar with RPR at all atm

**Comment by kaedys** [comment]
Eh, nothing has changed about the combos, so arguably just as relevant as it was prior to DT.  I still think it's likely to be a DPS loss in practice due to unexpectedly hitting gauge cap, but I don't really see a problem with the combo existing in the mod.  I could slap together a PR for it pretty quickly, too, (and since my reaper is 92, test it rather more easily than you, I think), if you'd like.

**Comment by MKhayle** [comment]
if you have time for it, I'd be glad to have help for Reaper for this issue and for #243 too
but if you don't, I'll just get it done after brainwashing myself

**Comment by kaedys** [comment]
Already started on the implementation this afternoon, I'll have a PR up once I get it working.  Same for 243, I'll include it in the same PR.

**Comment by MKhayle** [comment]
@kaedys was this addressed in the rework btw or not
I'm getting lost with all the RPR reworks we had

**Comment by kaedys** [comment]
Not in the one I already PR'd, but I do have it in the rework I'm currently testing today.
