### ISSUE TITLE
[Bug and Request] RPR Gluttony and Sacrificium

### ISSUE THREAD

**Issue by delphionic** [MKhayle/XIVComboExpanded#277]
Hi! Firstly with the bug, if you use the "Blood Stalk Gluttony Feature" and use Enshroud with Gluttony active, you're unable to use Lemure's Slice and it just shows a greyed out Gluttony.

![image](https://github.com/MKhayle/XIVComboExpanded/assets/35041046/d60aed60-aeac-44a2-849d-92feceb48b7f)

As for the request, is it possible for Sacrificium to replace Soul Slice while Enshrouded? It replaces Gluttony by default, but if you use the Blood Stalk Gluttony Feature it'd make a very convoluted button (I guess it'd be like: Blood Stalk > Gluttony and then Lemure's Slice > Sacrificium while Enshrouded).

Thanks!

**Comment by kaedys** [comment]
So, I think the major issue with putting it on Soul Slice is that it's an oGCD available as soon as you hit Enshroud, when ideally it should be weaved after the first or third Reaping attack (or the second and use Lemure's Slice after the third and fourth).  Replacing Soul Slice would require either tracking if the GCD is currently active, or would unconditionally use it before the first Reaping attack (assuming you're using the feature that puts Gibbet or Gallows on Soul Slice).

I think integrating it on top of Lemure's Slice (and Scythe) probably makes the most sense, where it replaces that button if it is available and you do not have 2 stacks of Void Shroud, with a sub-feature allowing that replacement even if you do have >= 2 Void Shroud (ie. allowing it to be prioritized over Lemure's Slice instead of behind it).  That results in you hitting the same button for the Sacrificium weave as you do for the Lemure's weaves.

**Comment by MKhayle** [comment]
Reaper has A LOT of options available (I think that's the job with most options available) so I'm not sure what an ideal setup would be for those actions. The aforementioned PR is expanding on 91+ compatibility but I overlooked 90- combos and when I will have some time and energy, I'll take a look at it.
