### ISSUE TITLE
[Bug] Machinist oGCD selection inconsistent with Gauss/Ricochet feature

### ISSUE THREAD

**Issue by kaedys** [MKhayle/XIVComboExpanded#305]
Think this is something else up with the new cooldown coded.  Especially during Hypercharge windows, the oGCD present is inconsistent between the two oGCD buttons (despite the fact that the logic _should_ return the same result), and often returns a result with fewer charges than the other.  Already investigating and debugging, just wanted to throw in an issue to make sure you were aware, @MKhayle, and in case anyone else encounters it.

**Comment by kaedys** [comment]
Discussion on #217 relevant for this one.

**Comment by vitharr137** [comment]
I believe the intent of the original CalcBestAction code is ultimately to use the actionID with the most available charges?

I could be oversimplifying it, however, this might be returned by using something similar to this code: 

`double[] remainingCooldownCompare = new int[]
{
    a1.Data.TotalCooldownRemaining,
    a2.Data.TotalCooldownRemaining,
};
int cooldownMinSearch = Enumerable.Range(0, RemainingCooldownCompare.Length).Aggregate((a, b) => (RemainingCooldownCompare[b] <= RemainingCooldownCompare[a]) ? b : a);
int cooldownMinSearch == 1 ? a2 : a1`

This is a bit of psuedocode, I'm mostly co-opting this from a check I use to calculate between redmage mana, like so:

`int[] manaIndex = new int[]
{
    whiteMana,
    blackMana,
};
int manaMinSearch = Enumerable.Range(0, manaIndex.Length).Aggregate((a, b) => (manaIndex[b] <= manaIndex[a]) ? b : a);
int manaMin = manaMinSearch == 1 ? blackMana : whiteMana;
int manaMax = manaMinSearch == 1 ? whiteMana : blackMana;`

**Comment by kaedys** [comment]
> I believe the intent of the original CalcBestAction code is ultimately to use the actionID with the most available charges?

Ish.  The intent is:

* If both abilities are at maximum charges or off cooldown, return the first ability.
* If only one of the two abilities is currently usable, return that ability.
* If both abilities are usable and only one uses charges, return the non-charge one.
* If both abilities are usable and both use charges, return the one that will cap on charges soonest.
* If neither ability is usable, return the one that will be usable first.

**Comment by MKhayle** [comment]
please uh
merge the current conversation in this one

**Comment by vitharr137** [comment]
So far I may have worked out a formula that fulfills all conditions, but it does require a new variable to return TotalBaseCooldown when TotalCooldownElapsed is 0 (I have not verified if the original cooldownElapsed still returns 0 on stack charges, that'll be next), because we want a smooth result from 0 to maximum. In this example, the cooldowns being compared are 1 'stack' of 60 seconds, and 3 stacks of 20 seconds, both equaling a TotalBaseCooldown of 60, but with different BaseCooldowns (60 and 20 respectively)

We'll call the new variable "RealCooldownElapsed" for now, I'm looking into how much breaks if I fix CooldownElapsed to read properly instead of being manually set to 0 when cooldowns are ready

`RealCooldownElapsed: return cooldownElapsed == 0 ? TotalBaseCooldown : cooldownElapsed;`

Importantly, this should return 0-59.99~ correctly, and also 60 when the actionID is 'offcooldown'

The intended result of this formula is to provide a number that can be compared, and the output should be the actionID with the highest calculated value

`Priority = (RealCooldownElapsed / BaseCooldown) + (IsCooldown * BaseCooldown)`

A few scenarios with this calculation:
`RealCooldownElapsed = 60`
| ActionID | BaseCooldown | RealCooldownElapsed | IsCooldown | Priority |
| --- | --- | --- | --- | --- |
60sec | 60 | 60 | 1 | 61
20sec/charge | 20 | 60 | 1 | 23

`RealCooldownElapsed = 58`
| ActionID | BaseCooldown | RealCooldownElapsed | IsCooldown | Priority |
| --- | --- | --- | --- | --- |
60sec | 60 | 58 | 0 | 0.97
20sec/charge | 20 | 58 | 1 | 22.9

`RealCooldownElapsed = 22`
| ActionID | BaseCooldown | RealCooldownElapsed | IsCooldown | Priority |
| --- | --- | --- | --- | --- |
60sec | 60 | 22 | 0 | 0.37
20sec/charge | 20 | 22 | 1 | 21.1

`RealCooldownElapsed = 2`
| ActionID | BaseCooldown | RealCooldownElapsed | IsCooldown | Priority |
| --- | --- | --- | --- | --- |
60sec | 60 | 2 | 0 | 0.03
20sec/charge | 20 | 2 | 0 | 0.1

The formula ensures the cooldown with the farthest to recover from gets recommended first if it is available, and otherwise, recommends the available action with the most charges first, and otherwise the one returning off cooldown the soonest. I'm not certain the best way to implement this into code

Another example against 3 actionIDs, this time with a different set of RealCooldownElapsed for their usages:

| ActionID | BaseCooldown | RealCooldownElapsed | IsCooldown | Priority |
| --- | --- | --- | --- | --- |
| 60sec | 60 | 60 | 1 | 61 |
| 20sec/chargeA | 20 | 44 | 1 | 22.2 |
| 20sec/chargeB | 20 | 22 | 1 | 21.1 |

**Comment by kaedys** [comment]
> We also need an inverse to IsCooldown, we'll say Ready, returning 1 if there is any charge available

We do already have that, `public bool Available => this.CooldownRemaining == 0 || this.RemainingCharges > 0;`

I'm examining the logic above in detail now, though, as well as the descriptions you provided in the other thread.  I'm going to use this issue for the convo on it going forwards, to avoid having to check both >.<

**Comment by vitharr137** [comment]
SMH, of course, apologies. I was too deep in math to look for existing ones, I'll edit that over and continue verifying cooldownElapsed's exact results

**Comment by vitharr137** [comment]
cooldownElapsed no longer has the issues with stacks I was noting last year, but it does still return 0 when the full cooldown is complete. The behavior is as follows:
Thunderclap: 3 charges, 30recharge, 90 full cooldown
cooldownElapsed increments positively, from >0 - 89.99~
cooldownElapsed returns 0 when the charges have fully recovered
it does not appear that cooldownElapsed is ever 0 unless all charges are off cooldown, but this is an extremely fast blip that I may be missing
cooldowns with only 1 'charge' (aka no charges) are treated the same, a charge exists only as a threshold on the total cooldown

I'll take a look at cooldownTotal now

**Comment by vitharr137** [comment]
cooldownTotal has an interesting interaction now. It does provide haste adjusted values, however it only returns non 0 results when the cooldown is active. Behavior is as follows:
Bootshine. 2sec Recast in game files, 1.948~ at my skill speed
cooldownTotal returns 0 while idle
cooldownTotal returns exact skillspeed value (1.948~) for Bootshine when cooldown is cycling after pressing, and does not change from that value during
cooldownTotal reverts to 0 when idle

**Comment by vitharr137** [comment]
isCooldown's original implementation on line 14, not my modified one, returns true if the cooldown is ticking in any way, and does not respect available stacks if they exist. It is simply true if there is any cooldown occuring at all, and false if there is not

**Comment by kaedys** [comment]
That is almost _definitely_ one of the major sources of issue with the new logic and CalcBestAction, because CalcBestAction assumes IsCooldown == is recharging in any capacity.  It does not assume that IsCooldown indicates the ability is _unusable_.  And given that we have Available for that already, I don't see why IsCooldown _shouldn't_ represent "is recharging in any capacity, even if it is also available for use currently".

**Comment by vitharr137** [comment]
I agree, Available working as expected now does make my new implementation of IsCooldown redundant and the only place I can find that I've implemented it in my own testing was in places where Available can take its place

**Comment by MKhayle** [comment]
I am not in a mental or physical state for nerding about this right now and the goal was to enhance the `CooldownData.cs` file so:

1- Either one of you (or you both together) bake a PR for the most sane way to do it
2- Either we just revert to the former `CooldownData.cs` file

2 would potentially be a loss but the easiest way to handle this, but I do believe 1 can greatly enhance the cooldowns management. I am trusting you both for this so feel free to take whatever decision you want about it

**Comment by kaedys** [comment]
Ya, I'm working on testing some of the changes per the above, will probably have to wait until after work to really dedicate to the task, though.

**Comment by vitharr137** [comment]
I'm stepping through each of my own additions to ensure they're useful and not duplication work and should have something to provide within the next hour is. I'll work on how to properly create a pull, that's something I haven't done before

BaseCooldown is important in how it does not revert to 0 like cooldownTotal does, and can be used to provide stable checks or calculations without needing to worry how the cooldownTotal shifts back to 0 repeatedly, so that so far is a new basis to additional checks later

**Comment by MKhayle** [comment]
feel free to share raw code in here if needed to, don't bother with a PR if kaedys can/want to make one honestly

**Comment by vitharr137** [comment]
Purpose of this overhaul: eliminate cooldownTotal from returning 0 to several calculation critical methods and deduplicate variables

Updated code so far:
`BaseCooldown`, `CastTime`, `Cost` all unchanged

`TotalBaseCooldown` updated:
```
public float TotalBaseCooldown
{
    get
    {
        var (cur, _) = Service.ComboCache.GetMaxCharges(this.ActionID);

        var total = this.BaseCooldown;

        return total * cur;
    }
}
```

I am debating the best intent for `CooldownTotal`, should it simply return the new, non-0 `TotalBaseCooldown`, or reflect `BaseCooldown` to represent potential stack cooldown as well as full cooldown values for stacks of 1?

`IsCooldown` removed, utilize the previous `isCooldown`. Optionally, can simply point to `isCooldown` instead to prevent further issues if it does not respect the lowercase "i" dynamically

`IsCapped` remains, mostly there as support for other forks' grammar, as an exact inverse to `isCooldown`, but `not isCooldown` could be used just the same, alright with this either staying or being removed

`CooldownElapsed` modified, now returns the positive incrementing seconds of each 'stack', and is capped at the stack's BaseCooldown, rather than reverting to 0
```
public float CooldownElapsed
{
    get
    {
        if (this.cooldownElapsed >= this.BaseCooldown
            || this.cooldownElapsed == 0)
            return this.BaseCooldown;

        return this.cooldownElapsed;
    }
}
```

`TotalCooldownElapsed` modified, now returns either the positively incrementing seconds of the total cooldown elapsed, or the total base cooldown, no longer reverting to 0
```
public float TotalCooldownElapsed
{
    get
    {
        if (this.cooldownElapsed == 0)
            return this.TotalBaseCooldown;

        return this.cooldownElapsed;
    }
}
```

No change to `TotalCooldownRemaining` but it will now properly return 0 when used to calculate against a cooldown that is not active thanks to the fixes to both cooldown elapsed methods

No changes to `CooldownRemaining`, `MaxCharges`, or `HasCharges`

`RemainingCharges` modified as it is no longer required to adjust for cooldownTotal returning 0
```
public ushort RemainingCharges
{
    get
    {
        return (ushort)(this.TotalCooldownElapsed / (this.TotalBaseCooldown / this.MaxCharges));
    }
}
```

No changes to `Available`, or `CooldownDuration` (despite this not functioning well, only properly working for actionIDs without charges. I am still hunting for a better way, if it exists, to do this)

`ChargeCooldownRemaining` modified, now pointing directly to `CooldownRemaining` as the repair to cooldownTotal returning 0 means this is no longer a special case, and seems to be playing nicely with testing for my own implementations currently
`public float ChargeCooldownRemaining => this.CooldownRemaining;`

`RecoveryTime` Unchanged, and now no longer loops back to full

`ChargeRecoveryTime` unchanged, and possibly able to be removed, but the class I use this as an edge case catch has not been updated on my side yet to officially check

`TotalChargeCooldownRemaining` and `TotalChargeRecoveryRemaining` now simply pointing to `TotalCooldownRemaining` now that it is reliable, and also a potential to be removed after I verify with the other classes:
`public float TotalChargeCooldownRemaining => this.TotalCooldownRemaining;`
`public float TotalChargeRecoveryRemaining => this.TotalChargeCooldownRemaining + this.BaseCooldown;`

Here is the file I've made so far, testing with MCH's CalcBestAction for Gauss/Ricochet does seem to properly alternate between them now, without any modification needed to the current `CalcBestAction`
[CooldownData.txt](https://github.com/user-attachments/files/16199504/CooldownData.txt)

I'd still like to chase a more algorithmic approach to these nested ifs in `CalcBestAction` but I believe this fixes the initial problem, if testing can be done to back that up :)

**Comment by kaedys** [comment]
What is the intended use case of `CooldownElapsed` with the capping applied to it?  I'm failing to intuit a case where that capping would be useful, especially given that other fields (such as `Available`) could be used more easily to determine if a charge is available.

Also, I realize some of this is to maintain compatibility with other forks, but given that a lot of these fields were _introduced_ in #217, I don't see much reason to retain any fields that didn't exist prior to those changes and aren't needed with the above refactoring.

**Comment by vitharr137** [comment]
Looking back through my older code for `CooldownElapsed`, I had used it when the game did not return other data fast enough to be acted upon, such as Hide for NIN or Manafont for BLM, but given the rest of the code has now been cleaned up to avoid using cooldownTotal, I do not have a reason to keep a separate, stack capped version of `CooldownElapsed` active at the moment, and I can indeed use Available and TotalCooldownElapsed instead, at least not without some deeper pondering on class nuance which isn't quite in scope for this bugfix or refactor

The other extra methods are my own musings and are likely better solved through other combinations of existing ones now that it's cleaned up more. I would need to continue fixing up my own code for these classes into Dawntrail to begin properly defending the other additions, and I don't mind at all what is decided to keep or discard depending on what others find obtuse or useful. I do apologize the abrupt upset from the previous inclusions, though, and hope it's a bit more clear overal

**Comment by kaedys** [comment]
For `CooldownElapsed`, I'm going to make it the mirror of `CooldownRemaining`, ie. `TotalCooldownElapsed` modulus `BaseCooldown`, which then represents the recharge elapsed on the currently recharging charge.

**Comment by kaedys** [comment]
ok, question.  We know the base game sets `cooldownElapsed` to 0 when the ability is off cooldown or fully recharged, but it also has `isCooldown`, and from prior comments it seems that this is also a base game value, and represents whether the ability is cooling down or recharging in any capacity at all (even if it is also currently usable because charges).  Can we not use `isCooldown` rather than `cooldownElapsed == 0` to return the "base" value (ex. `TotalBaseCooldown` for `TotalCooldownElapsed`), instead of _hoping_ that the game never returns exactly 0 for `cooldownElapsed` when the ability is actually recharging?  Do you see any issues with adjusting the logic in that way, @vitharr137?

**Comment by vitharr137** [comment]
I agree, that is served better as `isCooldown` 
New implementation of `TotalCooldownElapsed` looking more like this if I'm taking your meaning correctly?
```
public float TotalCooldownElapsed
{
    get
    {
        if (isCooldown == 0)
            return this.TotalBaseCooldown;

        return this.cooldownElapsed;
    }
}
```

`TotalBaseCooldown` should be calculating without any involvement of `cooldownElapsed` or `isCooldown`, just to confirm

**Comment by kaedys** [comment]
Since that can be inlined, I rewrote it as:

```
public float TotalCooldownElapsed => !this.isCooldown ? this.TotalBaseCooldown : this.cooldownElapsed;
```

**Comment by kaedys** [comment]
Ok, my compiled changes thus far:

- `IsCooldown` now just returns `isCooldown`.
- `TotalBaseCooldown` and `BaseCooldown` are as written above.
- Things that use to depend on `cooldownElapsed` or `CooldownElapsed` or `TotalCooldownElapsed` being 0 meaning the ability is not cooling down now simply use `!isCooldown`.
- `CooldownRemaining` no longer caps at `BaseCooldown`, and instead is a mirror of `CooldownElapsed`, being `TotalCooldownRemaining` modulus `BaseCooldown`, ie. the time remaining on the _next charge_.
- `TotalCooldownElapsed` matches the above behavior, where it will return `TotalBaseCooldown` when the ability is fully recharged.
- Anything that was dividing by `(TotalBaseCooldown / cur)` now instead divides by `BaseCooldown`, because it's mathematically the same and skips a call to get current charges.
- Removed the following fields as either redundant or not needed:
  - `CooldownTotal`
  - `IsCapped` (this is now equivalent to `!IsCooldown`)
  - `CooldownDuration` (equivalent to `CooldownElapsed`)
  - `ChargeCooldownRemaining` (now equivalent to `CooldownRemaining`)
  - `RecoveryTime`, `ChargeRecoveryTime`, `TotalChargeCooldownRemaining`, and `TotalChargeRecoveryRemaining` (because they are not currently needed, and if needed can be computed from other existing fields anyway).

I believe the result of this is should be that CalcBestAction can be simplified greatly, and most of the other logic stays the same, but I'm still working out the specifics.

I'm trying to build a new version of your above algorithm, because it breaks down in certain cases.  For example, if your 60s ability has an elapsed time of 12s and your 20s ability has an elapsed time of 2s, neither is available, and the 60s one won't be for another 48s, while the 20s one won't be for another 18s.  This means it _should_ return the 20s one, since it will be available soonest, but the calculated priority is 0.2 for the 60s one and 0.1 for the 20s one.

**Comment by kaedys** [comment]
Ok, here's what I've come up with to avoid the list of conditionals (though it _can_ be just a list instead of nesting, with the right ordering).

`priority = (-1 * !Available * CooldownRemaining) + (Available * (1000 - TotalCooldownRemaining))`

Basically, if the ability is _not_ currently available, the result will be a negative number representing the number of seconds until it is available, so larger (ie. more positive, not larger magnitude) means available sooner.  If the ability _is_ available, the result will be a positive number (so it _always_ takes priority over something not available) adjusted such that the ability with the shortest time until it reaches charge cap will have the largest value.  Thus we can simply directly compare the priority values and return the result.  I picked `1000` just because I needed an offset I could subtract from that was larger than any cooldown that would be seen in practice.  Any ability that is completely off cooldown will have a priority of 1000 with this algorithm.

**Comment by vitharr137** [comment]
I was just settling back down to get a few more iterations in on the formula, I'll run this through a few eyeball tests, but you've likely done more cases than I have on my own by now. I was most interested in adjusting this to a number to do more than 2 active compares, such as between MCH toolkit abilities, do you think it has that capability now?

**Comment by kaedys** [comment]
Yes, that number should now universally work for comparing abilities.  The goal traits for it, that it fulfills, are:

```
* Any ability that is off cooldown and at maximum charges has maximum (and equal) priority.
* If only one of the two abilities is currently usable, it has a higher priority.
* If both abilities are usable but recharging, the one that will cap soonest has higher priority.
* If neither ability is usable, the one that will be usable soonest has higher priority.
```

I threw it in an excel sheet and threw every manner of combinations I could think of at it, using one ability with 3 charges and a 20s recharge, and another with a 60s recharge and either 1 or 2 max charges, and it always returned the correct result according to the above criteria.

**Comment by kaedys** [comment]
Ok, that got REALLY simple.  The body of the function is now only 20 lines long, of which _14_ are documentation 🤣 (I tend towards extensive documentation, especially of complex code).

```C#
// This intent of this priority algorithm is to generate a single unified number that results in the 
// following behaviors:
//   * Any ability that is off cooldown and at maximum charges has maximum (and equal) priority.
//   * If only one of the two abilities is currently usable, it has a higher priority.
//   * If both abilities are usable but recharging, the one that will cap soonest has higher priority.
//   * If neither ability is usable, the one that will be usable soonest has higher priority.
//
// Mechanically, if the ability is not available, the result will be a negative number representing the
// seconds until it is available, so the closer to zero (ie. more positive) the number, the sooner it
// will be usable.  If the ability IS currently usable, the result will be a positive number (so always
// higher priority than an ability that is not currently usable), adjusted such that the ability with
// the shortest time until it reaches charge cap having the largest priority value.
// Any ability not currently cooling down will have a priority of 1000.
var a1Priority = a1.Data.Available ? (1000 - a1.Data.TotalCooldownRemaining) : -a1.Data.CooldownRemaining;
var a2Priority = a2.Data.Available ? (1000 - a2.Data.TotalCooldownRemaining) : -a2.Data.CooldownRemaining;

if (a1Priority == a2Priority)
    return original == a1.ActionID ? a1 : (original == a2.ActionID ? a2 : a1);

return a1Priority > a2Priority ? a1 : a2;
```

**Comment by vitharr137** [comment]
Well now! That looks right to me :D I've been trying to skip ahead a bit to see if it's possible to give more than 2 variables, some array of actionIDs to take the Max value from, but that definitely has done what I hoped it would in terms of replacing the original compare

**Comment by kaedys** [comment]
Hmm.  Problem.  It appears to be _working_ as expected, but it isn't changing the icon anymore, and I'm not sure why.  @MKhayle any ideas? I'm a bit lost as to how this is behaving this way, because it's _using_ the correct abilities when I press the button, it just isn't changing the icons.

**Comment by vitharr137** [comment]
One thing I've noticed when rebuilding the plugin several times is the graphic replacement seems to get stuck, and replacing the replaced actionID on the bar physically returns functionality. Notably, changing classes doesn't seem to do the trick, the button itself must be replaced

**Comment by kaedys** [comment]
Tried that (first thing I tried, actually), but I _think_ I found the issue.  Testing now.

**Comment by kaedys** [comment]
Yep, ok, it was actually an issue with the specific implementation of that combo on Machinist.  Originally, the conditional was:

```
        var richochet = level < MCH.Levels.CheckMate ? MCH.Ricochet : MCH.Checkmate;
        var gaussRound = level < MCH.Levels.DoubleCheck ? MCH.GaussRound : MCH.DoubleCheck;
        if (actionID == MCH.GaussRound || actionID == richochet)
```

I thought this odd, because one of the two was using the modified spell ID and one wasn't, so I corrected _both_ to, but apparently _that_ actually prevents the icon replacement.  I had to swap both to use the original base spell ID for the icon replacement to work.  So I recoded that entire section to not need the ternaries at all, since you can just `OriginalHook` the output of `CalcBestAction` anyway.

**Comment by kaedys** [comment]
Ok, this changed not just CalcBestAction, but many of the cooldown functions, as well as the underlying cooldown calculations, obviously.  I've thus far spot-checked the following combos, all of which use different variations of the cooldown functions, and they all work as expected:

* RDM Embolden to Manafiction
* RDM Fleche/Contre Sixte
* SGE Taurochole to Druochole
* SGE Toxikon to Phlegma (tests charges)
* MCH Gauss Round/Ricochet (charge-based version of the Fleche/Contre Sixte one)
* MCH Hot Shot/Air Anchor/Drill/Chainsaw (tests multiple abilities with differing cooldowns submitted.  I don't yet have Drill charges, though).

@MKhayle as this currently seems to be working as expected, I'm going to submit a PR for it.  However, given the volume of changes, I recommend it be quite thoroughly tested before merge, so we might want to tap some of the other active developers to run with a local build of it on various jobs and feature combinations.

**Comment by MKhayle** [comment]
(I'll test myself before pushing a live version)
