### ISSUE TITLE
[Request] Pictomancer Subtractive Pallet replace Fire in Red combo whenever available

### ISSUE THREAD

**Issue by Zynyx** [MKhayle/XIVComboExpanded#309]
**Describe the feature you'd like**
It's a new class and I just leveled it to 100, so I guess we could all say we have equal experience here, but I cannot imagine a use case where you would not want to use Subtractive Pallet every single time it is available. There is no timer on its stacks, so once it is up it will remain that way until you consume all of them. 

Can a more experienced Pictomancer tell me if I am I missing something here? If not, can we get this option added?

**Describe alternatives you've considered**

I do realize you will always want to have a subtractive pallet available for when you starry muse; however, Starry Muse makes your next subtractive pallet free- so that kind of seems moot. 

Thanks for your time MKhayle.

**Comment by MKhayle** [comment]
https://github.com/MKhayle/XIVComboExpanded/commit/b25db1092335ee802ff815850b455d2d37952a75 1.5.1.0 adds the requested features 

![image](https://github.com/user-attachments/assets/1ca03936-82b1-4f45-b4f7-c784c9a29d2e)

**Comment by Zynyx** [comment]
Thanks once again MKhayle!

**Comment by kaedys** [comment]
@MKhayle I suspect we should insert Subtractive with _either_ combo if the Subtractive Ready buff is active, since the entire design of the burst window is that you use Subtractive, Comet, and Star Prism as the 5 casts of Hyperphantasia.  You _always_ want to use Subtractive before casting any combo spells after using Scenic, there's never a situation you don't want to do that in, even under leveled.

@Zynyx as for why you would not want to cast Subtractive as soon as it is available, the main reasons are if you are pooling for upcoming burst, or if you're in a moderate movement situation where you can probably squeeze in the 1.5s standard combo casts but not the 2.3s Subtractive casts before having to move again, as using the combo casts is still technically a DPS gain over using Holy to cover the movement, if you can avoid delaying the GCD or overcapping.  For the burst, a good example is if there's only 1 mob left on a trash pack, using Subtractive to finish it off is sorta a waste compared to being able to drop 1 or even 2 Subtractive combos early in the next big trash pull (or on the upcoming boss).  There's at least 8 GCDs between hitting 50 gauge and having 100 gauge with the next GCD going to overcap, so that's _at least_ 20 seconds of wiggle room on when to cast it, and more if you fill with Holy and Hammer combo.  I generally see casting it as soon as it is available _as your default combo_ as probably a bad idea.  The overcap option is sufficient to avoid wasting the resource, and then you still have the option of using it early or back-to-back that way.

**Comment by MKhayle** [comment]
I need to rethink the Substractive combos now that we have access to gauges, and was about to rework some of them
Especially since I had a feedback about someone who had issues with some of the combos not working under specific conditions (which are: weird life choices as not opting for the Substractive ST/AoE Combos)

**Comment by kaedys** [comment]
I feel like it would be exceptionally odd to want the automatic usage of Subtractive but _not_ merging the Subtractive combo into the normal combo, if that's what you're implying >.>

**Comment by MKhayle** [comment]
this is exactly what I'm implying and I think I'm just going to make the auto-substractive features children of the substractive ST

**Comment by Zynyx** [comment]
That seems to make more sense @kaedys -- Sounds like the automatic usage of the Subtractive Combo is the better solution. I haven't really found myself in a situation where I could get off a 1.5 second cast, but not a 2.3; however, I'm usually pretty good at prepositioning myself as to avoid clipping. 

Thanks for all your work both of you!

**Comment by MKhayle** [comment]
> @MKhayle I suspect we should insert Subtractive with _either_ combo if the Subtractive Ready buff is active, since the entire design of the burst window is that you use Subtractive, Comet, and Star Prism as the 5 casts of Hyperphantasia. You _always_ want to use Subtractive before casting any combo spells after using Scenic, there's never a situation you don't want to do that in, even under leveled.

it's been done btw https://github.com/MKhayle/XIVComboExpanded/commit/f85a965eb3bf0235be72ed09155916b06f490b4d

**Comment by MKhayle** [comment]
I'll temporarily consider PCT "done" and focus on the rest now (AST, NIN & VPR, notably)
