### ISSUE TITLE
[Bug] Paladin's Requiescat/Imperator wouldn't turn into Blade of Honor if #136 is turned on

### ISSUE THREAD

**Issue by HPDeskJet2540** [MKhayle/XIVComboExpanded#346]
**Describe the bug**
In the game's default setting, Requiescat/Imperator will turn into the lvl 100 skill Blade of Honor, however if the "Requiescat Fight or Flight" is enabled, the Requiescat/Imperator wouldn't turn into Blade of Honor.
**To Reproduce**
Please try to submit as much information as possible to reproduce the behavior:
1. Which plugin version you have: v1.5.1.9
2. Which job is affected: Paladin
3. What are your enabled combos for that job: Requiescat Fight or Flight Feature, Confiteor Feature, Royal Authority Combo.
4. Which skill is placed in your hotbar: Royal Authority, Holy Spirit, Atonement, Fight or Flight
5. Are you using any other XIVCombo fork? because you shouldn't: No

**Expected behavior**
The Requiescat/Imperator should turn into Blade of Honor after using Blade of Valor
**Screenshots or videos**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by kaedys** [comment]
Ah, just responded to your #345 with pointing to this combo.  I know this happens with the Requiescat Confiteor combo enabled.  It definitely _should_ also happen without that enabled, but just with Requiescat FoF and Confiteor Feature enabled.  I can put in a quick fix for that, though I'd like to wait for your answer on #345, since that would be included, depending on your answer.

**Comment by HPDeskJet2540** [comment]
Hello, I have replied in #345, thank you so much for your work!

**Comment by MKhayle** [comment]
2.0.0.0 https://github.com/MKhayle/XIVComboExpanded/commit/16215df0faef50a0a7796e33dfafc9f508d4ab56 is out, and should have fixed this issue. If it doesn't, please re-open this issue!
