### ISSUE TITLE
[Request] Summoner: Summon X -> Searing Flash when Searing Demi Feature active

### ISSUE THREAD

**Issue by corsair980** [MKhayle/XIVComboExpanded#371]
**Describe the feature you'd like**
An update to the Searing Demi Feature to turn the Summon button into Searing Flash while Ruby's Glimmer is active

**Describe alternatives you've considered**
Alternatively, Ruin III and/or Tri-Disaster could be changed to Searing Flash under Ruby's Glimmer, however this would conflict with other available options for Summoner

**Additional context**
Currently, Searing Flash is inaccessible by default with Searing Demi Feature active as Searing Light normally turns into Searing Flash under Ruby's Glimmer but the button becomes unavailable when Searing Flash is on cooldown with this feature active

**Comment by kaedys** [comment]
If we do it as an extension of Searing Demi, we should probably make sure to condition it on Ruby Glimmer being active _and_ Summon Bahamut/Phoenix being on cooldown, because otherwise it'd try to do Searing Light -> Searing Flash -> Summon, which could delay the Summon GCD.

That said, the Searing Demi feature is already sub-optimal with the change in duration of Searing Light to 20s, as the current opener and 2-minute combos _both_ use the Demi summon _before_ Searing Light, rather than after it as the combo feature currently expects (which I suspect is a relic of back when Searing Light _couldn't_ be case after the Demi summon, since it was executed by the carbuncle instead of the summoner).  It should probably just now swap to Searing Light if the Demi summon is _on_ cooldown and either Searing Light is off CD or Ruby's Glimmer is active.

**Comment by MKhayle** [comment]
It's probably a relic of EW, yes.

**Comment by kaedys** [comment]
And _early_ EW, I believe.  Pretty sure they fixed that in like 6.1 or so.  There just wasn't much of a need to change it at the time, because Searing being 30s meant that you _usually_ wanted to use it _before_ the Demi summon anyway.

**Comment by MKhayle** [comment]
We will probably take a look at this during our second pass of #323

**Comment by MKhayle** [comment]
I'm looking at it now

**Comment by MKhayle** [comment]
Will be available with 2.0.0.0's release

**Comment by MKhayle** [comment]
2.0.0.0 https://github.com/MKhayle/XIVComboExpanded/commit/16215df0faef50a0a7796e33dfafc9f508d4ab56 is out, and should have fixed this issue. If it doesn't, please re-open this issue!
