### ISSUE TITLE
[Request] RPR: Shadow of Death option improvements

### ISSUE THREAD

**Issue by TheTweets** [MKhayle/XIVComboExpanded#403]
**Describe the feature you'd like**
The problem with the Shadow of Death to Gibbet/Gallows options is losing access to Shadow of Death while Enshrouded; I'd like to suggest splitting it in two - the option to replace it while Reaving, and the option to replace it while Enshrouded. The Reaving portion would be under the Expanded header, while the Enshrouded portion would be under the Accessiblity header.

For example, if I select Reaving but not Enshrouded: 
- If I have the Soul Reaver or Executioner buff, Shadow of Death is replaced with Gibbet/Gallows.
- If I have the Enshrouded buff, Shadow of Death is not replaced with anything.
- If I have neither, Shadow of Death is not replaced with anything.

**Describe alternatives you've considered**
This could be some kind of sub-option of the existing feature, selecting what we have now but having an option labelled "Only while Reaving" and "Only while Enshrouded" for example. I don't think this is the ideal method however as it would lock a 'lower-tier' option behind a 'higher-tier' one.

**Additional context**
Right, so the problem with replacing Shadow of Death is Enshroud locking you out of basically everything else, meaning you can't shuffle GCDs around while Enshrouded and can't refresh the debuff either. While technically this could also happen while Reaving, you're never Reaving for more than 2 GCDs, and using anything other than Gibbet/Gallows already drops the stacks, meaning you're pseudo-locked into them by the vanilla mechanics anyway.

Therefore I reckon that Shadow to Gibbet/Gallows could be an 'Expanded'-level feature _if and only if_ it doesn't do anything in Enshroud. Best of both worlds!

**Comment by MKhayle** [comment]
@kaedys can you handle that one?
we have reached 45 combos on this damned job and people are still asking for more

**Comment by kaedys** [comment]
Honestly, I just _strongly_ recommend not using the Shadow of Death versions of those features.  We were seriously considering removing them entirely, because Shadow of Death _is_ used during Enshroud.  In fact, it's one of the few non-Enshroud actions that isn't just straight locked out by Enshroud.  I strongly recommend using Soul Slice instead of Shadow of Death for your other of Gibbet/Gallows.

Still, I could see splitting that option.  I honestly think it's a mistake to go down that road, though, and as MKhayle points out, Reaper right now has far more features than any other job, and a lot of that is because of _duplicate_ features like this.

**Comment by TheTweets** [comment]
> Honestly, I just _strongly_ recommend not using the Shadow of Death versions of those features. We were seriously considering removing them entirely, because Shadow of Death _is_ used during Enshroud. In fact, it's one of the few non-Enshroud actions that isn't just straight locked out by Enshroud. I strongly recommend using Soul Slice instead of Shadow of Death for your other of Gibbet/Gallows.
> 
> Still, I could see splitting that option. I honestly think it's a mistake to go down that road, though, and as MKhayle points out, Reaper right now has far more features than any other job, and a lot of that is because of _duplicate_ features like this.

To clarify, I'm actually suggesting the existing feature be replaced, as this is essentially just an improvement to it. Rather than further bloating the terrifyingly-large list of options, you'd have a "Shadow [Gibbet/Gallows] Feature" that replaces Shadow of Death only while Reaving, and then a sub-option locked behind Accessibility that also replaces it while Enshrouded, due to exactly the reason you mentioned - you _really_ don't want to have it replaced while Enshrouded!

Just as a personal thing due to how I ended up having a comfortable hotbar layout, Soul Slice doesn't... Fit(?) Gibbet/Gallows. To make it work I've had to use the Shadow of Death stuff, but I've long been annoyed at the Enshroud clunkiness that introduces. My goal here is to fix that, without needlessly adding more bloat. 

As for the bloat; I totally agree. I think there's some room to condense these options, at least on the user-facing end; I intend to go through them and see if I can figure something out, but that's a separate matter!

**Comment by kaedys** [comment]
I already managed to condense _some_ of them in the 2.0 update, by merging some of the single target and AoE options together.  I've got a local branch where I'm working on a couple other Reaper features, I'll add this to the list.

**Comment by Nelpheras** [comment]
I feel like the whole Soul Reaver section clutter hinges a lot on having too much modularity.
Is there really a use case where you would replace Infernal Slice with Gibbet/Gallows but not Soul Slice with the other? It feels odd to have one swapping button and a default one to handle reaving.
Also "Slice Enhanced Soul Reaver Feature" is just a combination of different replacement combos above which should work with the autoswap "Gibbet/Gallows Enhanced Feature" but dont.

A good way of condensing all the mono Soul Reaver section would be to just have 2 combos offering different levels of accessibility and enhancement and make them compatible with each other:

	Combo 1: Replace both Infernal Slice and Soul Slice with Gibbet and Gallows (-2 buttons, you can still press the wrong one)
		Maybe a sub-option to swap to Gallows and Gibbet for preference

	Combo 2: Replace Gibbet and Gallows with whichever is enhanced (-1 button, you can never press the wrong one)
		Sub-option: Replace Shadow of Death with the above only when not enshrouded (-2 buttons, you can never press the wrong one)

Combo 2 already exists ("Gibbet/Gallows Enhanced Feature") but doesnt work with the current replacement combos.
Having all of this active would mean Infernal Slice, Soul Slice and Shadow of Death would all swap to the correct reaving button.
This would replace all 8 current combos.

**Comment by MKhayle** [comment]
![image](https://github.com/user-attachments/assets/a5932bd2-24d6-4c79-9bb4-321aeccfc3c3)

**Comment by kaedys** [comment]
> Is there really a use case where you would replace Infernal Slice with Gibbet/Gallows but not Soul Slice with the other?

Isn't this issue _exactly that?!_  The OP wants to continue to use Shadow of Death, _not_ Soul Slice, as the other of Gibbet and Gallows.  And if you're proposing instead one combo that replaces Infernal Slice with one of the two and _both_ Shadow of Death and Soul Slice with the other, I think that's a sledgehammer fix, tbh.

> Combo 2: Replace Gibbet and Gallows with whichever is enhanced (-1 button, you can never press the wrong one)
>	Sub-option: Replace Shadow of Death with the above only when not enshrouded (-2 buttons, you can never press the wrong one)

This is also a problem for me.  I use the Slice Enhanced Enshrouded Feature but NOT the Slice Enhanced Soul Reaver Feature, because the mod auto-selecting during Enshroud doesn't matter at all, but auto-selecting between Gibbet and Gallows _absolutely does_, since those are both positional abilities.  So if we merge those together, you're left with being forced to auto-select between positionals outside Enshroud, or NOT being able to auto-select during Enshroud.

That all said, I do think we can trim at least a _few_ by making the features that replace Gibbet and Gallows (or Guillotine) directly also apply to any features that place Gibbet or Gallows (or Guillotine) on other buttons.  I'll see what I can put together.

**Comment by lhn1703** [comment]
> That all said, I do think we can trim at least a _few_ by making the features that replace Gibbet and Gallows (or Guillotine) directly also apply to any features that place Gibbet or Gallows (or Guillotine) on other buttons. I'll see what I can put together.

Good luck, I shall leave this cursed job in your capable hands while I take an indefinite vacation to Eksuplosion land.

**Comment by kaedys** [comment]
Fortunately, Reaper is one of the jobs I've contributed most to (and _played_ the most, for that matter), so I know the file and features rather well.  <puts on combat helmet>

**Comment by MKhayle** [comment]
Look, my setup works for me.
Just add an option to re-enable Gibet into Gallows with fries and a Slice of cheese.

**Comment by kaedys** [comment]
...so, completely unrelated, I'm actually seriously considering adding a feature to Bard that lets you replace a _completely arbitrary_ ability ID with the song replacement cycle, which would then depend on ReAction's ability to place any action ID you input onto whatever hotbar slot you want.  So you can tell ReAction to place something like Sleep on your _Bard_ bar, which is legal according to the game but completely unusable for obvious reasons, and then have the song replacement use _that_ button so it doesn't replace any of the songs directly and thus you can always see the cooldown of all 3 songs when using that cycle feature.

You may "that's horrifying" as desired.

**Comment by MKhayle** [comment]
that's horrifying and also I hope you aren't truly serious

**Comment by kaedys** [comment]
I'm definitely considering it.  But I may just not bother, given that I have Bard at 97, and I fully intend to park it until 8.0 as soon as it hits 100, because it is by far my least favorite of the phys ranged.

**Comment by kaedys** [comment]
Ok, this is going to be a pretty major revision, and no I'm not even remotely sorry about that.  But I'm merging a LOT of features along the lines of:

>making the features that replace Gibbet and Gallows (or Guillotine) directly also apply to any features that place Gibbet or Gallows (or Guillotine) on other buttons. 

For example, we have 4 separate features _each_ for adding Lemure's Slice/Scythe and Communio onto various other attacks (Slice, Soul Slice, Shadow of Death, Nightmare Scythe).

With my changes, Reaper now has 36 combos: 3 `Single Target`, 2 `Area of Effect`, 13 `Soul Reaver`, 8 `Enshroud`, and 7 `Miscellaneous`.  I have all of the combos themselves updated, now to revise 700 lines of Reaper file code to handle the changes >.>

**Comment by TheTweets** [comment]
> > Is there really a use case where you would replace Infernal Slice with Gibbet/Gallows but not Soul Slice with the other?
> 
> Isn't this issue _exactly that?!_ The OP wants to continue to use Shadow of Death, _not_ Soul Slice, as the other of Gibbet and Gallows. And if you're proposing instead one combo that replaces Infernal Slice with one of the two and _both_ Shadow of Death and Soul Slice with the other, I think that's a sledgehammer fix, tbh.
> 
> > Combo 2: Replace Gibbet and Gallows with whichever is enhanced (-1 button, you can never press the wrong one)
> > Sub-option: Replace Shadow of Death with the above only when not enshrouded (-2 buttons, you can never press the wrong one)
> 
> This is also a problem for me. I use the Slice Enhanced Enshrouded Feature but NOT the Slice Enhanced Soul Reaver Feature, because the mod auto-selecting during Enshroud doesn't matter at all, but auto-selecting between Gibbet and Gallows _absolutely does_, since those are both positional abilities. So if we merge those together, you're left with being forced to auto-select between positionals outside Enshroud, or NOT being able to auto-select during Enshroud.
> 
> That all said, I do think we can trim at least a _few_ by making the features that replace Gibbet and Gallows (or Guillotine) directly also apply to any features that place Gibbet or Gallows (or Guillotine) on other buttons. I'll see what I can put together.

It's now 3am for me so I'm going to go pass out and try to remember to look back tomorrow, but I've managed to cook up a layout for RPR's features that reduces the up-front vomit of features down to 15 by nesting things. I have no clue what sort of difficulties would be presented on the coding end but perhaps this can serve as a jumping-off point.

Basically, all the duplicate features are just nested as options of a super-feature; do you want to replace skills with Reaver skills? Toggle the Reaver Feature and choose which ones you want to enable.

Here's the doc I used; I tried to colour code it and use indentation to make things legible: https://docs.google.com/document/d/1DKMudVkhp6m75M1fsaCcI89U290zYIrJLprsYs1sBwA/edit?usp=sharing

**Comment by kaedys** [comment]
I don't think we gain anything but having "does nothing on its own" features just so we can have things as subfeatures, tbh.

**Comment by kaedys** [comment]
So, for example, I've merged _all_ of the Gluttony features into a single feature that replaces Blood Stalk, Grim Swathe, and any other action that is replaced by either of those with Gluttony when available.  There's now only ONE feature for automatic selection of Gibbet or Gallows based on the buff, and it applies to _any_ action replaced by Gibbet or Gallows.  I used similar logic for a lot of trimming.

**Comment by kaedys** [comment]
Ok, I'm going to split off my couple of bugfixes into a separate PR and finish coding and testing these changes tomorrow.

**Comment by TheTweets** [comment]
> I don't think we gain anything but having "does nothing on its own" features just so we can have things as subfeatures, tbh.

So here's where I'm coming from: I don't think that the number of features RPR has is _per se_ a problem, rather I think the problem is the fact that the number of features presented to you is overwhelming, and the number of features is just a part of what causes that. 

Collapsible menus for the stuff that all does functionally the same thing (Gallows replacing X skill versus Gibbet replacing X skill, or Communio replacing Y, Z, A, and/or B) streamlines the mental task, even if the number of options available to you is still the same. That addresses the problem by making the same thing feel less overwhelming.

It sounds like you're addressing the problem from the other side: reducing the number of options in the first place, which naturally reduces the number of features presented to you. I'm looking forward to seeing what you cook up!

**Comment by kaedys** [comment]
But subfeatures aren't collapsible.  Not everyone has the "hide child features" toggle set (I certainly don't, since the "parent" feature doesn't necessarily tell the whole story of whether I'd find it useful).  I think we'd actually gain more mileage by potentially being more granular with our categories.  13 features under `Soul Reaver` might be too many.  I'll see what I can do with that.

**Comment by MKhayle** [comment]
> But subfeatures aren't collapsible. 
.............. should we? I mean, if RPR didn't exist, I wouldn't even ask, but... that'd be doable (but it'd hurt my imgui brain again)

**Comment by kaedys** [comment]
Maybe.  Or maybe collapsible sections would work better.  Reaper doesn't actually _have_ that many subfeatures, especially with the rework I'm doing, since it's instead designed to just work with other features.  Only 8 of the 39 features are sub-features, under 6 parent features.  Collapsing the groupings would probably do a lot more in that avenue.

**Comment by kaedys** [comment]
@MKhayle Is there a way to automagically pop up the changelog for the plugin?  Or otherwise trigger a notification box similar to the 2.0 notification?  The changes to Reaper are significant enough that I want to make sure users will be aware of them.

**Comment by MKhayle** [comment]
I'd rather avoid popping up a changelog with each release, especially with the number of releases we're having. 
I may try working on a system to specify in a changelog entry whether to display a pop-up, but also, pop-ups are a pain to deal with (and users absolutely hate them and 90% of them don't read it)

**Comment by kaedys** [comment]
I _love_ the one from DelvUI, though.  It's super handy for spotting changes to job gauges and stuff that I need to go configure.  And anyone actually using the Reaper features currently is definitely going to need to update their selections

**Comment by MKhayle** [comment]
I'm not using DelvUI so I've never seen that changelog

**Comment by kaedys** [comment]
<img width="321" alt="20240810-204551-cd691c" src="https://github.com/user-attachments/assets/a8b8d7bf-ceb7-46da-90cb-9314312686c3">

This is what the Delv one looks like.  Very handy for knowing about new features I need to react to by changing settings.

I think it'd probably make sense to also have an option to entirely suppress the "important changes happened" pop-up (ie. opt-out), and maybe a separate option (opt-in) to always open the XIV-CE window and go directly to the changelog when the mod is updated.  So we don't have a pop-up for every change, just important ones that can or will affect current combo setups that users need to react to, and then users can opt _out_ of that pop-up if they hate pop-ups no matter how relevant, and a separate option where users can opt _in_ to always know when an update happened and what changed in it, via the changelog (which isn't a separate pop-up, it just auto-opens the main interface and goes to that tab).

But also I know how much you hate ImGui after this revamp, so that's all just spitballing.  I'd just like _some_ way to alert users that all the combos they were using have probably changed a lot and they need to reconfigure their combo options.

**Comment by MKhayle** [comment]
I mean, that's something I could do. 
But that'd be probably be an opt-in feature. 
And that wouldn't be immediately ready, at least not for the RPR rework.

**Comment by kaedys** [comment]
Unfortunate.  I hope users aren't too upset by their combos suddenly not working.  And more to the point, I hope they discover that during, like, a FATE or something and not their first pull on Savage reclears >.>

**Comment by MKhayle** [comment]
Just type "wait, my mouse broke" while you fix it!

**Comment by kaedys** [comment]
"BRB my goldfish is on fire"
