### ISSUE TITLE
[Request] "Steel Coil Feature" Swap Flank/Rear

### ISSUE THREAD

**Issue by biomagnet** [MKhayle/XIVComboExpanded#424]
Just a silly request, but the ability to have Swiftskin's Coil replace Steel Fangs and Hunter's Coil replace Reaving Fangs instead, as I personally put the rear positionals first, then the flank, where it matters. Mostly a muscle memory aid.

**Comment by kaedys** [comment]
So, the reason they are the way they are is that they match which positional comes from which button.  The 2nd combo hit on Steel Fangs always leads to a flank positional, so Steel Fangs is replaced by Hunter's Coil, which is also a flank positional, and vice versa for Reaving.  The intent was to align the positional muscle memory around the 2nd hit with the same positional on the Winder attacks.

I don't _necessarily_ see an issue with swapping them, however.  But it may be worth just swapping Reaving and Steel on your bar instead.  After all, Reaving is the one that leads to a rear positional, so having Reaving first on your bar would align with your normal ordering logic better.  Incidentally, I have the same ordering thing, my rear positionals go on 2, my flanks on 3, so I have Reaving on 2 and Steel on 3 to match that.  That's also why I wrote that feature to swap them in like that, because it means my Winder replacements also align with 2 = rear, 3 = flank.

Downside of that, of course, is that the Vipersight gauge appears to be _hardcoded_ for Steel being before Reaving on the bar, which is incredibly stupid, imo.  However, you can get around that by using another mod to replace or adjust the job gauge (DelvUI's is quite good, imo, though it is designed to replace much more than just the job gauges).  Or ditch the Vipersight gauge entirely, use Job Bars or Gauge-O-Matic to make a separate Rattling Coil tracker, and just follow the combo highlight on your bar instead of the pretty mediocre job gauge.

**Comment by biomagnet** [comment]
You know, I genuinely just tend to hit the shining buttons and never really noticed which mid-combo leads to which end-combo. That's an incredibly insightful answer that I very much appreciate! I don't look at the Viper job gauge much; I have Steel first because it comes first when synced down, etc. (even if realistically I'd never be synced down so far as to not have both of them) but you do make compelling arguments. It's also just to align with the way I have it on other jobs since I'm a dirty omni-player and try to, for instance, always have my distance attack on 8 no matter the job, if that makes sense.

I've been playing with Gauge-O-Matic recently and may see if I can use it to wrap my head around the combo system and what the bars are trying to say at any one time better.  Thank you!

**Comment by kaedys** [comment]
I legitimately love Gauge-O-Matic.  It's like everything I wanted JobBars to be, but better.  I have two bars setup on it to let me track the two 2nd-combo buffs, since DelvUI (which I use for most of my job bars currently) doesn't have trackers for those like they do for other jobs with rotational buffs.  I'm seriously considering just hard swapping all of my job bar implementations over to Gauge-O-Matic, though (but that'll be a _ton_ of initial setup work >.<)

**Comment by kaedys** [comment]
Also, in case you didn't see my edit above, Gauge-O-Matic has a tweak to reverse the Vipersight gauge.  And another tweak to make the highlight color based on positional type.

**Comment by biomagnet** [comment]
I'm reading up now. It looks promising! I can try to look into all that too, so thank you for the tip. I'd still appreciate an option to swap them just to match with the PVP matching option, even if it's silly, but I understand there are other options available to me, as well.

As an aside, what's the text option to pull up the window for XIV Combo Expanded? It isn't /pcombo and it's not /xivcomboexpanded, unless I'm doing something wrong.

**Comment by kaedys** [comment]
`/pcombo` is the correct command for it.  Odd if that's not working for you.

**Comment by MKhayle** [comment]
If you have another XIVCombo fork (or the original XIVCombo) installed, that may cause a conflict.

**Comment by MKhayle** [comment]
Also, uh, I think this was a non-issue, so I'll close it
