### ISSUE TITLE
[Request] RPR: replace Soul Scythe with Guillotine

### ISSUE THREAD

**Issue by debonairdead** [MKhayle/XIVComboExpanded#433]
There's an <i>Expanded<i> option to put Gibbet or Gallows onto Soul Slice, but there's no option to put Guillotine on Soul Scythe. Is this something that can be done? "Soul Guillotine Feature" please and thank you.

**Comment by kaedys** [comment]
I mean, possibly, but the Soul Slice feature is already marked as heavily discouraged.  Beyond that, the only reason the Shadow and Soul Slice replacements for Gibbet/Gallows exist is because there are two of them, and only one of those two can be placed on the central Slice combo button without delving into auto-selection logic (and probably missing half your positionals).  So those feature exist to put whichever of Gibbet and Gallows is NOT on the main Slice combo button.

Guillotine has no such need, since there's no pair to it like there is with Gibbet and Gallows.  Why not use the Nightmare Scythe replacement option instead?

**Comment by debonairdead** [comment]
I'm currently using Scythe Guillotine paired with replacement features, it's an accessibility feature I <i>absolutely adore</i> and, as a player that isn't into serious raiding, I'm not really fussed about missing a positional every now and then. And as far as Nightmare Guillotine goes, it's not a <i>deal breaker</i> by any stretch it's just personal preference. I like things to match, I like my hotbars setup specifically.

So, with that said, if it's a 'no' then I'll just have to deal with it.

**Comment by kaedys** [comment]
The primary concern I have is that Shadow of Death and Whorl of Death are the only two non-Enshroud attacks usable while Enshrouded.  Granted, the double Enshroud window doesn't really matter at all in _most_ situations where Whorl is being used, but Shadow of Death at least is a very important button in Enshroud, as it's the only reason that a double-Enshroud sequence is even feasible.  I generally resist feature that further lean into eclipsing Shadow or Whorl of Death with other buttons, especially Enshroud buttons.

Still, we _do_ have a version of that for single target, so I'll leave it up to @MKhayle on whether we take this one up or not.

**Comment by kaedys** [comment]
Wait a minute, I just realized you're asking for _Soul Scythe_, not Whorl of Death.  Ugh, my reading comprehension apparently suffers quite heavily when I'm on vacation.

Ya, for Soul Scythe, full send, I see no reason not to have that feature available.  I'm actually a bit surprised I didn't go ahead and implement it already when I did the Reaper rework recently >.<

**Comment by debonairdead** [comment]
Fantastic! Glad to hear it, I look forward to the implementation.
