### ISSUE TITLE
[Bug] Stardiver to Nastrond

### ISSUE THREAD

**Issue by IndigoAura** [MKhayle/XIVComboExpanded#453]
Stardiver to Nastrond doesn't seem to work properly? it turns to Geirskogul properly, and turns into Nastrond during Life of Dragon, but only turns to Stardiver for a fraction of a second before being Nastrond again? after Nastrond charges are spent it stays Nastrond and misses Stardiver entirely.

**Comment by kaedys** [comment]
I _suspect_ it is because we're using `IsCooldownUsable(DRG.Nastrond)`.  That check should instead be looking for the `Nastrond Ready` buff, since Nastrond doesn't really have a cooldown anymore.  Quick and easy fix.

On that note, we should probably have a subfeature to tell it to prioritize Stardiver over Nastrond anyway.

**Comment by kaedys** [comment]
Alright, fixed the bug affecting Nastrond, and implemented new features that allow the user to prioritize Stardiver over Nastrond and/or Dragonfire Dive.  Also, the Nastrond and Dragonfire Dive replacements are no longer mutually-exclusive features (with the latter having priority if both are selected and available), and Stardiver and Dragonfire Dive both respect the base game Action Change Settings for whether they also include Starcross and Rise of the Dragon, respectively.
