### ISSUE TITLE
[Request] SGE - Eukrasia Replacements

### ISSUE THREAD

**Issue by Jaesaces** [MKhayle/XIVComboExpanded#457]
**Request:**
Set of mutually exclusive options to replace Eukrasia when you have the Eukrasia buff:
  1. Eukrasian Diagnosis
  2. Eukrasian Dosis
  3. Eukrasian Prognosis
  4. Eukrasian Dyskrasia

**Alternative:**
Replacing Diagnosis with Eukrasia (when above level 30) could similarly save a button since there's hardly any situations where you should be using regular Diagnosis.

**Comment by kaedys** [comment]
For Dosis, we do have the auto-use option, which replaces Dosis with Eukrasia when your current target either lacks Dosis or only has a short time left on it.  Not quite the ask here, but can provide at least some functionality there in the mean time.

I don't really see an issue with these.  Eukrasia isn't an oGCD like Aetherflow, but these features are essentially of a kind with the various Aetherflow replacement options for SCH (though obviously a rather different use-case).  I'd probably also include an option to always replace Prognosis with Eukrasia, since standard Prognosis is similarly very rarely used, especially once you have Pepsis (since that lets Euk Prog give a 450p AoE heal for 900 mp, vs. 300p for 800 without Eukrasia and Pepsis).

**Comment by MKhayle** [comment]
I'll add those mutually exclusive options soon

**Comment by MKhayle** [comment]
Should be fixed/done in https://github.com/MKhayle/XIVComboExpanded/commit/4a7ba95fc6e247ed4a2954bacd9a20cb6848b4ea
