### ISSUE TITLE
[Request] RPR: Replace Harpe with Sacrificium

### ISSUE THREAD

**Issue by Propagandist1** [MKhayle/XIVComboExpanded#473]
When Enshrouded, RPR gets the Oblatio buff which allows one use of Sacrificium.  Sacrificium is a 25y range instant cast ability that consumes Oblatio.  Seems like it could feasibly replace Harpe when Enshrouded.  

The other abilities get kinda crowded and confusing when putting Sacrificium on them... and it seems like one might appreciate Sacrificium replacing the dedicated "ranged attack" ability.

**Comment by kaedys** [comment]
As I commented on the PR, it feels like a somewhat odd replacement to make, if for no other reason than that Sacrificium is an oGCD.  Ideally, you shouldn't be exiting melee range at all during Enshroud, so integrating it with the ranged button feels weird to me.  Still, I don't really see any issue with such a combo existing.

**Comment by Propagandist1** [comment]
I see your point.  If it doesn't fit with the theme of the plugin, or doesn't make as much sense gameplay-wise, then I would be happy to let this one go.  RPR certainly has an enormous amount of features already.

Really, I just was struggling with button placement.  RPR has a lot of button bloat as it is, since there's ST and AOE versions of similar abilities (whorl/shadow, slice/scythe, stalk/swathe).  I usually have AOE stuff on my mouse, with ST stuff on my keyboard.  Helps keep me doing combos correctly in ST vs. AOE situations.  But the damn Sacrificium only replaces Gluttony, which I don't ever press because there's a feature to put Gluttony on Stalk/Swathe, when available.  I figured this might be a way to put Sacrificium on another button that everyone's gonna have anyway.  

If you have an alternative suggestion for Sacrificium placement, I'd like to hear your thoughts.  Maybe there's something obvious I'm missing.  
- Maybe a feature to put it on Stalk/Swathe, but usable after you've done both Lemure's?  
- Maybe stick it on Enshroud but take priority over Communio?

**Comment by kaedys** [comment]
I guess I just see it as weird because, despite having a 25y range, Sacrificium isn't a _ranged attack_, or at least, it shouldn't be _thought of_ as one.  It's an oGCD that just happens to have a longer range so you don't get screwed out of it if you have to disengage.  But the combo doesn't actually cause any _problems_, nor does it, imo, encourage bad habits, so I don't really have an issue with it.

We _do_ already have a feature to replace Lemure's Slice/Scythe (ie. Stalk/Swathe) with it, replacing when you have fewer than 2 Void Shroud stacks (purple orbs), meaning the 1st and 3rd weave windows.  It's under the Enshroud section of the combos, called "Lemure's Sacrificium Feature".

**Comment by Propagandist1** [comment]
Yeah, I noticed that Lemure's Sacrificium Feature.  My issue with it is that it's tied more concretely to the number of Void Shroud stacks, which leads to some awkward behavior.  For example:
1. Enshroud (Stalk is replaced by Lemure's Slice, which is not usable yet) (Gives 5 Lemure Shroud stacks)
2. Void Reaping (Stalk is replaced by Sacrificium) (Changes to 4 Lemure Shroud stacks, 1 Void Shroud stacks)
3. Cross Reaping (Stalk is replaced by Lemure's Slice, which we will use) (Changes to 3 Lemure Shroud stacks, 2 Void Shroud stacks)
4. Lemure's Slice (Stalk is replaced by Lemure's Slice, which is not usable now) (Changes to 3 Lemure Shroud stacks, 0 Void Shroud stacks)
5. Void Reaping (Stalk is replaced by Sacrificium) (Changes to 2 Lemure Shroud stacks, 1 Void Shroud stacks)
6. Cross Reaping (Stalk is replaced by Lemure's Slice, which we will use) (Changes to 1 Lemure Shroud stacks, 2 Void Shroud stacks)
7. Lemure's Slice (Stalk is replaced by Lemure's Slice, which is not usable now) (Changes to 1 Lemure Shroud stacks, 0 Void Shroud stacks)
8. Communio (consumes remaining Lemure Shroud stack)

Now, technically Sacrificium is available to use at any time during this sequence of events just by pressing the Gluttony button.  But we're disgusting combo degenerates, which is why we're gathered here together this evening.  :)  My goal is to find somewhere/somehow for Sacrificium to be blended into the above in a way that works.  One could modify the Lemure's Sacrificium Feature to, at minimum, allow Stalk/Swathe to turn into Sacrificium on Step 8.  That would be consistent with my first bulleted recommendation above.  Could also allow it to be used on Step 1 and Step 4, I guess.  To achieve that, you could just change the:

```
                if (IsEnabled(CustomComboPreset.ReaperLemuresSacrificiumFeature))
                {
                    if (level >= RPR.Levels.Sacrificium && HasEffect(RPR.Buffs.Oblatio) &&
                        (gauge.LemureShroud == 2 || (gauge.LemureShroud == 4 &&
                        !IsEnabled(CustomComboPreset.ReaperSacrificiumAdvancedFeature))))
                        return RPR.Sacrificium;
                }

```
conditional on all the abilities to a simple:

```
                if (IsEnabled(CustomComboPreset.ReaperLemuresSacrificiumFeature))
                {
                    if (level >= RPR.Levels.Sacrificium && HasEffect(RPR.Buffs.Oblatio) &&
                        (gauge.LemureShroud == 2 || (gauge.LemureShroud != 2 &&
                        !IsEnabled(CustomComboPreset.ReaperSacrificiumAdvancedFeature))))
                        return RPR.Sacrificium;
                }
```
to allow Sacrificium to be used on Stalk/Swathe whenever Lemure's Slice is unavailable (or only on the 3rd weave if ReaperSacrificiumAdvancedFeature is selected), or 
```
                if (IsEnabled(CustomComboPreset.ReaperLemuresSacrificiumFeature))
                {
                    if (level >= RPR.Levels.Sacrificium && HasEffect(RPR.Buffs.Oblatio) &&
                        (gauge.LemureShroud <= 2 || (gauge.LemureShroud == 4 &&
                        !IsEnabled(CustomComboPreset.ReaperSacrificiumAdvancedFeature))))
                        return RPR.Sacrificium;
                }
```
to allow Sacrificium to be used on Stalk/Swathe on the 1st weave (conditionally on the ReaperSacrificiumAdvancedFeature), 3rd weave, and after you've used both Lemure's.  But that seems more complicated than the first option.  

Or lastly:

```
                if (IsEnabled(CustomComboPreset.ReaperLemuresSacrificiumFeature))
                {
                    if (level >= RPR.Levels.Sacrificium && HasEffect(RPR.Buffs.Oblatio) &&
                        (gauge.LemureShroud == 1 || (gauge.LemureShroud != 1 &&
                        !IsEnabled(CustomComboPreset.ReaperSacrificiumAdvancedFeature))))
                        return RPR.Sacrificium;
                }
```
to allow Sacrificium to be used on Stalk/Swathe whenever Lemure's Slice is unavailable (or only after both Lemure's usages, if ReaperSacrificiumAdvancedFeature is selected).

I'm kind of thinking out loud here, and I've derailed the original feature request.  But this is I guess an "alternative" that would achieve a similar end-result to what I'm proposed.  What do you think?  

Thank you again for explaining things to me, and for entertaining these thoughts!

**Comment by kaedys** [comment]
I guess I'm a bit confused.  While _technically_ you can weave Sacrificium immediately after Enshroud, I don't believe that is generally recommended.  Outside of that, you have 3 viable sequences for the oGCDs:

* Lemures after 2nd and 4th, Sacrificium after 1st
* Lemures after 2nd and 4th, Sacrificium after 3rd
* Lemures after 3rd and 4th, Sacrificium after 2nd (after 1st is an identical Sac location as the first bullet, even if you delayed the first Lemures)

Our automatic use combos support the first two already.  The default Lemure's Sacrificium puts it in the 1st weave slot, and it can instead be delayed to the 3rd using the secret combo `Sacrificium 3rd Weave`.  The third bullet is extremely niche and is probably best handled by explicitly using Sacrificium via the Gluttony button and Lemures via the Stalk/Swathe buttons.

> For example, consider this sequence of actions:

I don't see the issue here.  You can freely use Sacrificium after number 2 or 5 in that sequence without any loss, as those are the two free weave windows.  The current replacement logic, whether you auto-include it on the Reapings or just replace Stalk/Swathe, already supports exactly this, as you noted.  Sacrificium is available for use, and properly replaces Stalk/Swathe, between 2 and 3, and between 5 and 6.

> One could modify the Lemure's Sacrificium Feature to, at minimum, allow Stalk/Swathe to turn into Sacrificium on Step 8. That would be consistent with my first bulleted recommendation above. Could also allow it to be used on Step 1 and Step 4, I guess

All of those involve clipping.  Using it after 1 (Enshroud) only works if you early-weaved Enshroud, and is generally not recommended due to buff alignment and potential for clipping.  Using it after 4 or prior to 8 both involve double-weaving it after a Lemures, which is guaranteed to clip, since Enshroud runs on 1.5s GCDs.

**Comment by Propagandist1** [comment]
Aaahh, I see what you're saying.  I wasn't understanding the clipping problem.  It seems as though Sacrificium was implemented in this way for the ReaperLemuresSacrificiumFeature because it is optimal: one should use the ability at the first or third weave because that's the only places it'll fit without clipping.

See, I thought it would just make for a nice 1, 2, 3, (3) 1, 2, 3, (3) combo to fit it in after one of the Lemure's, but I understand now that it would result in clipping.  I wanted to just be able to slip Sacrificium in the sequence anywhere that Lemure's wasn't executable.  I'm going to close the original pull request, as it seems you both have already thought this through.

However, do you think there's merit in still having Sacrificium on Stalk/Swathe when Lemure's Slice is not executable, or even if Lemure Shroud is at 1?  I'm thinking in scenarios where you're either:
- Pushed out of melee range due to a knockback, and you might as well just burn Sac
- You forgot or missed the button, somehow
Or would that perhaps encourage "bad" behavior?  Again, thank you for the detailed responses.

**Comment by Propagandist1** [comment]
Alright.  I'm not certain what's the best way to tweak it.  For now, I'm going to just go with the feature as-is.  I'll close the issue, since this thread has given me a lot of knowledge on how to best resolve my issue!
